### ISSUE TITLE
NoSuchMethodError for prepareExists using version 0.0.5 with 0.19.11

### ISSUE THREAD

**Issue by triggs** [tlrx/elasticsearch-test#10]
```
   private static final String INDEX = "items";

   @ElasticsearchNode(name = "someNodeName", clusterName = "some-cluster-name", local = true, data = true)
   Node someNodeName;
   @ElasticsearchClient(nodeName = "someNodeName") 
   Client client;

   @Test
   @ElasticsearchIndex(indexName = "items", forceCreate = true) 
   @ElasticsearchBulkRequest(dataFile = "documents/bulk1.json") 
   public void testSomething() throws IOException {

       SearchResponse response = client.prepareSearch(INDEX).setQuery(QueryBuilders.matchAllQuery()).execute().actionGet();
       assertEquals(7L, response.hits().totalHits());
   }
```

is causing this error

java.lang.NoSuchMethodError: org.elasticsearch.client.IndicesAdminClient.prepareExists([Ljava/lang/String;)Lorg/elasticsearch/action/admin/indices/exists/indices/IndicesExistsRequestBuilder;
    at com.github.tlrx.elasticsearch.test.support.junit.handlers.annotations.ElasticsearchIndexAnnotationHandler.buildIndex(ElasticsearchIndexAnnotationHandler.java:139)
    at com.github.tlrx.elasticsearch.test.support.junit.handlers.annotations.ElasticsearchIndexAnnotationHandler.handleBefore(ElasticsearchIndexAnnotationHandler.java:42)
    at com.github.tlrx.elasticsearch.test.support.junit.rules.ElasticsearchTestRule.executeBeforeOrAfterMethodHandlers(ElasticsearchTestRule.java:62)
    at com.github.tlrx.elasticsearch.test.support.junit.rules.ElasticsearchTestRule.before(ElasticsearchTestRule.java:38)
    at com.github.tlrx.elasticsearch.test.support.junit.rules.AbstractElasticsearchRule$1.evaluate(AbstractElasticsearchRule.java:59)
    at org.junit.rules.RunRules.evaluate(RunRules.java:20)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
    at com.github.tlrx.elasticsearch.test.support.junit.rules.AbstractElasticsearchRule$1.evaluate(AbstractElasticsearchRule.java:62)
    at org.junit.rules.RunRules.evaluate(RunRules.java:20)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
    at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
    at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

**Comment by derryos** [comment]
Also seeing this issue. 

Using 0.0.5 with ES 0.20.x works fine. Does not work with 0.19.x

Is their a publicly available 0.0.4 that we can use?

**Comment by derryos** [comment]
Have tested using a locally available 0.0.4-snapshot and 0.19.9/11 - is working ok. Is it possible to either get a 0.0.4 publicly or a 0.0.5 with 0.19.x compatibility?

**Comment by tlrx** [comment]
Hi, sorry for the delay. Do you still need a 0.0.4/0.0.5 version of the API or are you planning to update to a more recent version of elasticsearch?

**Comment by derryos** [comment]
No problem - we actually just ended up moving to 0.20.4 and using 0.0.7 :-)

**Comment by triggs** [comment]
We've updated so I'll close it, I don't expect the rapid pace of ElasticSearch development to slow down anytime soon and time would be better spent on keeping up with them rather fixing oler stuff so I'll close this off.
