### ISSUE TITLE
es-test 0.0.9 / es-0.90.3 incompatibility in DeleteTemplates

### ISSUE THREAD

**Issue by gquintana** [tlrx/elasticsearch-test#23]
elasticsearch-test 0.0.9 can not be used with elasticsearch-0.90.3

```
java.lang.NoSuchMethodError: org.elasticsearch.cluster.metadata.MetaData.getTemplates()Lorg/elasticsearch/common/collect/ImmutableMap;
    at com.github.tlrx.elasticsearch.test.request.DeleteTemplates.getTemplates(DeleteTemplates.java:78)
    at com.github.tlrx.elasticsearch.test.request.DeleteTemplates.execute(DeleteTemplates.java:89)
    at com.github.tlrx.elasticsearch.test.request.DeleteTemplates.execute(DeleteTemplates.java:40)
    at com.github.tlrx.elasticsearch.test.EsSetup.doExecute(EsSetup.java:148)
    at com.github.tlrx.elasticsearch.test.EsSetup.execute(EsSetup.java:132)
```

**Comment by tlrx** [comment]
This should be fixed wiith the next release.
