### ISSUE TITLE
Test Failure in 0.0.11-SNAPSHOT

### ISSUE THREAD

**Issue by marksievers** [tlrx/elasticsearch-test#25]
```
Results :

Tests in error: 
  testLocalTransportClient(com.github.tlrx.elasticsearch.test.annotations.ElasticsearchTransportClientAnnotationTest): No node available

Tests run: 32, Failures: 0, Errors: 1, Skipped: 0

```

Surefire report...

```
elasticsearch-test$less target/surefire-reports/com.github.tlrx.elasticsearch.test.annotations.ElasticsearchTransportClientAnnotationTest.txt 

-------------------------------------------------------------------------------
Test set: com.github.tlrx.elasticsearch.test.annotations.ElasticsearchTransportClientAnnotationTest
-------------------------------------------------------------------------------
Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 6.44 sec <<< FAILURE!
testLocalTransportClient(com.github.tlrx.elasticsearch.test.annotations.ElasticsearchTransportClientAnnotationTest)  Time elapsed: 0.044 sec  <<< ERROR!
org.elasticsearch.client.transport.NoNodeAvailableException: No node available
        at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:205)
        at org.elasticsearch.client.transport.support.InternalTransportClusterAdminClient.execute(InternalTransportClusterAdminClient.java:85)
        at org.elasticsearch.client.support.AbstractClusterAdminClient.nodesInfo(AbstractClusterAdminClient.java:147)
        at org.elasticsearch.action.admin.cluster.node.info.NodesInfoRequestBuilder.doExecute(NodesInfoRequestBuilder.java:123)
        at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:85)
        at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:59)
        at com.github.tlrx.elasticsearch.test.annotations.ElasticsearchTransportClientAnnotationTest.testLocalTransportClient(ElasticsearchTransportClientAnnotationTest.java:58)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
        at com.github.tlrx.elasticsearch.test.support.junit.rules.AbstractElasticsearchRule$1.evaluate(AbstractElasticsearchRule.java:62)
        at org.junit.rules.RunRules.evaluate(RunRules.java:18)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
        at com.github.tlrx.elasticsearch.test.support.junit.rules.AbstractElasticsearchRule$1.evaluate(AbstractElasticsearchRule.java:62)
        at org.junit.rules.RunRules.evaluate(RunRules.java:18)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
        at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:35)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:115)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:97)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.maven.surefire.booter.ProviderFactory$ClassLoaderProxy.invoke(ProviderFactory.java:103)
        at com.sun.proxy.$Proxy0.invoke(Unknown Source)
        at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:150)
        at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcess(SurefireStarter.java:91)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:69)
```

Reproduces via `mvn test` and via Eclipse.

Great library BTW!

**Comment by zwegner** [comment]
A coworker just saw this issue, and I believe it's because a local elasticsearch instance is running. If you close it down, the problem should go away.
